//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class partnicsEntities : DbContext
    {
        public partnicsEntities()
            : base("name=partnicsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<td_part_result> td_part_result { get; set; }
        public DbSet<tm_metal_weight> tm_metal_weight { get; set; }
        public DbSet<tm_workcenter_stamp> tm_workcenter_stamp { get; set; }
        public DbSet<td_part_delivery> td_part_delivery { get; set; }
        public DbSet<tm_workcenter_bonding> tm_workcenter_bonding { get; set; }
        public DbSet<td_part_progress> td_part_progress { get; set; }
        public DbSet<td_part_recdata> td_part_recdata { get; set; }
        public DbSet<tt_part_stat> tt_part_stat { get; set; }
    }
}
