//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qimnicsEntities : DbContext
    {
        public qimnicsEntities()
            : base("name=qimnicsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tm_workcenter> tm_workcenter { get; set; }
        public DbSet<tr_curing_nics> tr_curing_nics { get; set; }
        public DbSet<tr_job_progress_nics> tr_job_progress_nics { get; set; }
        public DbSet<tr_metal_job_nics> tr_metal_job_nics { get; set; }
        public DbSet<tr_part_nics> tr_part_nics { get; set; }
    }
}
