//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_job_tps_info
    {
        public string rack_no { get; set; }
        public string order_date { get; set; }
        public string order_time { get; set; }
        public string order_user { get; set; }
        public string receive_date { get; set; }
        public string receive_time { get; set; }
        public string receive_user { get; set; }
        public string supply_date { get; set; }
        public string supply_time { get; set; }
        public string supply_user { get; set; }
        public string takeout_date { get; set; }
        public string takeout_time { get; set; }
        public string takeout_user { get; set; }
        public string job_order_no { get; set; }
        public string parent_job_order_no { get; set; }
        public string tag_no { get; set; }
        public string cure_date { get; set; }
        public string kanban_no { get; set; }
        public Nullable<short> kanban_qty { get; set; }
        public string company_code { get; set; }
        public string location_cd { get; set; }
        public string plant_code { get; set; }
        public string data_no { get; set; }
        public string part_item { get; set; }
        public string parent_item { get; set; }
        public string part_wc { get; set; }
        public string fg_wc { get; set; }
        public string group_cd { get; set; }
        public string machine_no { get; set; }
        public string job_status { get; set; }
        public string batch1 { get; set; }
        public string batch2 { get; set; }
        public string batch3 { get; set; }
        public string batch4 { get; set; }
        public string batch5 { get; set; }
        public string batch6 { get; set; }
        public string batch7 { get; set; }
        public string batch8 { get; set; }
        public string compound { get; set; }
        public Nullable<double> qty { get; set; }
        public string unit { get; set; }
        public string job_type { get; set; }
        public string pgm_mode { get; set; }
        public string tcs_no { get; set; }
        public string trans_sign { get; set; }
    }
}
