//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_job_information
    {
        public string job_no { get; set; }
        public Nullable<short> suffix { get; set; }
        public string tag_no { get; set; }
        public string item { get; set; }
        public string job_status { get; set; }
        public string location_cd { get; set; }
        public string wc { get; set; }
        public string machine_no { get; set; }
        public string group_cd { get; set; }
        public string batch { get; set; }
        public string batch2 { get; set; }
        public string batch3 { get; set; }
        public string batch4 { get; set; }
        public string batch5 { get; set; }
        public string batch6 { get; set; }
        public string batch7 { get; set; }
        public string batch8 { get; set; }
        public string compound { get; set; }
        public Nullable<double> weight { get; set; }
        public string expire_date { get; set; }
        public string order_box { get; set; }
        public Nullable<short> order_number { get; set; }
        public string order_date { get; set; }
        public string order_time { get; set; }
        public string order_user { get; set; }
        public string receive_box { get; set; }
        public Nullable<short> receive_number { get; set; }
        public string receive_date { get; set; }
        public string receive_time { get; set; }
        public string receive_user { get; set; }
        public string supply_box { get; set; }
        public Nullable<short> supply_number { get; set; }
        public string supply_date { get; set; }
        public string supply_time { get; set; }
        public string supply_user { get; set; }
        public string takeout_box1 { get; set; }
        public Nullable<short> takeout_number1 { get; set; }
        public string takeout_box2 { get; set; }
        public Nullable<short> takeout_number2 { get; set; }
        public string takeout_box3 { get; set; }
        public Nullable<short> takeout_number3 { get; set; }
        public string takeout_box4 { get; set; }
        public Nullable<short> takeout_number4 { get; set; }
        public string takeout_date { get; set; }
        public string takeout_time { get; set; }
        public string takeout_user { get; set; }
        public Nullable<short> compound_qty { get; set; }
        public Nullable<short> prepare_status { get; set; }
        public string plan_machine { get; set; }
        public Nullable<double> curing_time { get; set; }
        public Nullable<short> qc_inspection { get; set; }
        public string inspect_date { get; set; }
        public string inspect_time { get; set; }
        public string inspect_user { get; set; }
        public Nullable<short> item_master { get; set; }
        public Nullable<short> size { get; set; }
        public string size_desc { get; set; }
        public Nullable<short> spare_sign { get; set; }
        public string spare_box { get; set; }
        public string rubbertag1 { get; set; }
        public string rubbertag2 { get; set; }
        public string rubbertag3 { get; set; }
        public string rubbertag4 { get; set; }
        public string rubbertag5 { get; set; }
        public string fifo_batch { get; set; }
        public string job_order_no { get; set; }
        public string kanban_no { get; set; }
        public string job_type { get; set; }
        public string pgm_mode { get; set; }
        public string unit { get; set; }
        public string trans_sign { get; set; }
    }
}
