//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_kanban_info
    {
        public string transection_no { get; set; }
        public string file_sign { get; set; }
        public Nullable<short> part_type { get; set; }
        public string job_no { get; set; }
        public Nullable<short> suffix { get; set; }
        public string status { get; set; }
        public string due_date { get; set; }
        public string due_time { get; set; }
        public string cure_date { get; set; }
        public string item { get; set; }
        public string description { get; set; }
        public Nullable<int> total_tag_no { get; set; }
        public Nullable<double> qty_tag { get; set; }
        public Nullable<double> container_qty { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string wc { get; set; }
        public string parent_job { get; set; }
        public Nullable<short> parent_suffix { get; set; }
        public string tag_no { get; set; }
        public string parent_item { get; set; }
        public string location_cd { get; set; }
        public string group_cd { get; set; }
        public string parent_wc { get; set; }
        public string parent_mc { get; set; }
        public string rack_no { get; set; }
        public string order_date { get; set; }
        public string order_time { get; set; }
        public string order_user { get; set; }
        public string receive_date { get; set; }
        public string receive_time { get; set; }
        public string receive_user { get; set; }
        public string supply_date { get; set; }
        public string supply_time { get; set; }
        public string supply_user { get; set; }
        public string complete_date { get; set; }
        public string complete_time { get; set; }
        public string complete_user { get; set; }
        public Nullable<short> print_sign { get; set; }
        public Nullable<short> delay_sign { get; set; }
        public string job_order_no { get; set; }
        public string parent_job_order_no { get; set; }
        public string kanban_no { get; set; }
        public string trans_sign { get; set; }
        public string batch1 { get; set; }
        public string batch2 { get; set; }
    }
}
