//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_part_delivery
    {
        public string part_job_order_no { get; set; }
        public string part_code { get; set; }
        public string parent_job_order_no { get; set; }
        public string finished_goods_code { get; set; }
        public string delivery_no { get; set; }
        public string wc { get; set; }
        public string group_name { get; set; }
        public string plant { get; set; }
        public Nullable<int> qty { get; set; }
        public string truck_no { get; set; }
        public string cart_no { get; set; }
        public string working_shift { get; set; }
        public string print_status { get; set; }
        public string print_date { get; set; }
        public string print_time { get; set; }
        public string print_user { get; set; }
        public string loading_status { get; set; }
        public string loading_date { get; set; }
        public string loading_time { get; set; }
        public string loading_user { get; set; }
        public string receiving_status { get; set; }
        public string receiving_date { get; set; }
        public string receiving_time { get; set; }
        public string receiving_user { get; set; }
        public string incoming_date { get; set; }
        public string incoming_time { get; set; }
        public Nullable<int> qty_box { get; set; }
        public string tag_no { get; set; }
        public Nullable<int> machine_no { get; set; }
        public string part_type { get; set; }
    }
}
