//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_part_recdata
    {
        public string part_item { get; set; }
        public Nullable<int> qty_tag { get; set; }
        public Nullable<int> container_qty { get; set; }
        public Nullable<int> basket_num { get; set; }
        public Nullable<int> basket_qty { get; set; }
        public string user_id { get; set; }
        public Nullable<System.TimeSpan> insert_time2 { get; set; }
        public string wc { get; set; }
        public string stat { get; set; }
        public string job_order_no { get; set; }
        public string tag_no { get; set; }
        public string entry_user { get; set; }
        public string wc_cure { get; set; }
        public string mc_cure { get; set; }
        public string mc_part { get; set; }
        public int id { get; set; }
        public string finished_goods_code { get; set; }
        public Nullable<System.TimeSpan> update_time2 { get; set; }
        public Nullable<int> insert_date { get; set; }
        public Nullable<int> update_date { get; set; }
        public string insert_time { get; set; }
        public string update_time { get; set; }
    }
}
