//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_part_progress
    {
        public string data_type { get; set; }
        public string item { get; set; }
        public Nullable<short> oper_num_00 { get; set; }
        public string wc_00 { get; set; }
        public string check_sign_00 { get; set; }
        public string result_sign_00 { get; set; }
        public Nullable<short> oper_num_01 { get; set; }
        public string wc_01 { get; set; }
        public string check_sign_01 { get; set; }
        public string result_sign_01 { get; set; }
        public Nullable<short> oper_num_02 { get; set; }
        public string wc_02 { get; set; }
        public string check_sign_02 { get; set; }
        public string result_sign_02 { get; set; }
        public Nullable<short> oper_num_03 { get; set; }
        public string wc_03 { get; set; }
        public string check_sign_03 { get; set; }
        public string result_sign_03 { get; set; }
        public Nullable<short> oper_num_04 { get; set; }
        public string wc_04 { get; set; }
        public string check_sign_04 { get; set; }
        public string result_sign_04 { get; set; }
        public Nullable<short> oper_num_05 { get; set; }
        public string wc_05 { get; set; }
        public string check_sign_05 { get; set; }
        public string result_sign_05 { get; set; }
        public Nullable<short> oper_num_06 { get; set; }
        public string wc_06 { get; set; }
        public string check_sign_06 { get; set; }
        public string result_sign_06 { get; set; }
        public Nullable<short> oper_num_07 { get; set; }
        public string wc_07 { get; set; }
        public string check_sign_07 { get; set; }
        public string result_sign_07 { get; set; }
        public Nullable<short> oper_num_08 { get; set; }
        public string wc_08 { get; set; }
        public string check_sign_08 { get; set; }
        public string result_sign_08 { get; set; }
        public Nullable<short> oper_num_09 { get; set; }
        public string wc_09 { get; set; }
        public string check_sign_09 { get; set; }
        public string result_sign_09 { get; set; }
        public Nullable<short> oper_num_10 { get; set; }
        public string wc_10 { get; set; }
        public string check_sign_10 { get; set; }
        public string result_sign_10 { get; set; }
        public Nullable<short> oper_num_11 { get; set; }
        public string wc_11 { get; set; }
        public string check_sign_11 { get; set; }
        public string result_sign_11 { get; set; }
        public Nullable<short> oper_num_12 { get; set; }
        public string wc_12 { get; set; }
        public string check_sign_12 { get; set; }
        public string result_sign_12 { get; set; }
        public Nullable<short> oper_num_13 { get; set; }
        public string wc_13 { get; set; }
        public string check_sign_13 { get; set; }
        public string result_sign_13 { get; set; }
        public Nullable<short> oper_num_14 { get; set; }
        public string wc_14 { get; set; }
        public string check_sign_14 { get; set; }
        public string result_sign_14 { get; set; }
        public Nullable<short> oper_num_15 { get; set; }
        public string wc_15 { get; set; }
        public string check_sign_15 { get; set; }
        public string result_sign_15 { get; set; }
        public Nullable<short> oper_num_16 { get; set; }
        public string wc_16 { get; set; }
        public string check_sign_16 { get; set; }
        public string result_sign_16 { get; set; }
        public Nullable<short> oper_num_17 { get; set; }
        public string wc_17 { get; set; }
        public string check_sign_17 { get; set; }
        public string result_sign_17 { get; set; }
        public Nullable<short> oper_num_18 { get; set; }
        public string wc_18 { get; set; }
        public string check_sign_18 { get; set; }
        public string result_sign_18 { get; set; }
        public Nullable<short> oper_num_19 { get; set; }
        public string wc_19 { get; set; }
        public string check_sign_19 { get; set; }
        public string result_sign_19 { get; set; }
        public string inspection_0 { get; set; }
        public string judge_0 { get; set; }
        public string inspection_1 { get; set; }
        public string judge_1 { get; set; }
        public string inspection_2 { get; set; }
        public string judge_2 { get; set; }
        public string inspection_3 { get; set; }
        public string judge_3 { get; set; }
        public string inspection_4 { get; set; }
        public string judge_4 { get; set; }
        public string job_order_no { get; set; }
        public Nullable<System.TimeSpan> insert_time2 { get; set; }
        public Nullable<System.TimeSpan> update_time2 { get; set; }
        public Nullable<int> insert_date { get; set; }
        public Nullable<int> update_date { get; set; }
        public string insert_time { get; set; }
        public string update_time { get; set; }
    }
}
