//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_rubber_batch
    {
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string entry_user { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string update_user { get; set; }
        public string location_cd { get; set; }
        public string wc { get; set; }
        public string machine_no { get; set; }
        public string group_cd { get; set; }
        public string parts_job_order_no { get; set; }
        public string job_order_no { get; set; }
        public string lot_no { get; set; }
        public string parts_item { get; set; }
        public string finished_goods_code { get; set; }
        public string compound { get; set; }
        public string batch1 { get; set; }
        public string batch2 { get; set; }
        public string batch3 { get; set; }
        public string batch4 { get; set; }
        public string batch5 { get; set; }
        public string batch6 { get; set; }
        public string batch7 { get; set; }
        public string batch8 { get; set; }
        public string batch9 { get; set; }
        public string batch10 { get; set; }
    }
}
