//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class td_rubber_info
    {
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string curing_date { get; set; }
        public string parts_job_order_no { get; set; }
        public string parent_job_order_no { get; set; }
        public Nullable<int> part_qty { get; set; }
        public string parts_item { get; set; }
        public string parent_item { get; set; }
        public string eng_code { get; set; }
        public string wc { get; set; }
        public string machine_no { get; set; }
        public string parts_tag_no { get; set; }
        public string description { get; set; }
        public string location_cd { get; set; }
        public string group_cd { get; set; }
        public string curing_job_order_no { get; set; }
        public Nullable<int> curing_qty { get; set; }
        public Nullable<int> cycle_time { get; set; }
        public string curing_tag_no { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> prepare_sign { get; set; }
        public string kanban_no { get; set; }
        public string buffer_date { get; set; }
        public string buffer_time { get; set; }
        public string buffer_user { get; set; }
        public string order_date { get; set; }
        public string order_time { get; set; }
        public string order_user { get; set; }
        public string rcv_date { get; set; }
        public string rcv_time { get; set; }
        public string rcv_user { get; set; }
        public string due_date { get; set; }
        public string due_time { get; set; }
        public string sent_date { get; set; }
        public string sent_time { get; set; }
        public string sent_user { get; set; }
        public string completed_date { get; set; }
        public string completed_time { get; set; }
        public string completed_user { get; set; }
        public string urgent_date { get; set; }
        public string urgent_time { get; set; }
        public string urgent_user { get; set; }
        public Nullable<int> delay_sign { get; set; }
        public string delay_date { get; set; }
        public string delay_time { get; set; }
        public string delay_user { get; set; }
        public Nullable<int> cancel_sign { get; set; }
        public Nullable<int> order_advance { get; set; }
        public string next_process { get; set; }
        public string program_name { get; set; }
        public string prepare_job_order_no { get; set; }
        public string order_type { get; set; }
        public string compound { get; set; }
        public Nullable<int> re_order_sign { get; set; }
        public string last_curing_job { get; set; }
        public Nullable<int> disp_re_order { get; set; }
    }
}
