//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_metal_weight
    {
        public string finished_goods_code { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string user_name { get; set; }
    }
}
