//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_workcenter_stamp
    {
        public string wc { get; set; }
        public string wc_name { get; set; }
        public string location_cd { get; set; }
        public string machine_no { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> scn_machine { get; set; }
        public Nullable<int> scn_job_part { get; set; }
        public Nullable<int> scn_spec { get; set; }
        public Nullable<int> scn_material { get; set; }
        public string entry_date { get; set; }
        public string entry_time { get; set; }
        public string entry_user { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string update_user { get; set; }
    }
}
