//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_workcenter
    {
        public string file_sign { get; set; }
        public string active_sign { get; set; }
        public string entry_date { get; set; }
        public string update_date { get; set; }
        public string update_time { get; set; }
        public string update_wsid { get; set; }
        public string update_pgm { get; set; }
        public string update_sign { get; set; }
        public string wc { get; set; }
        public string wc_name { get; set; }
        public string group_name { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public string cost_code { get; set; }
    }
}
