//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_curing_nics
    {
        public string record_status { get; set; }
        public Nullable<int> entry_date { get; set; }
        public Nullable<int> entry_time { get; set; }
        public Nullable<int> update_date { get; set; }
        public Nullable<int> update_time { get; set; }
        public string entry_terminal_id { get; set; }
        public string program_id { get; set; }
        public string update_user_code { get; set; }
        public string company_code { get; set; }
        public string plant_code { get; set; }
        public string job_order_no { get; set; }
        public string data_transfer_complete_sign { get; set; }
        public string err_sign { get; set; }
        public string parent_job_order_no { get; set; }
        public string divide_sign { get; set; }
        public string manufactured_curing { get; set; }
        public string list_type_rubber { get; set; }
        public string list_type_parts { get; set; }
        public string purchase_order { get; set; }
        public string process_sign7 { get; set; }
        public string process_sign8 { get; set; }
        public string process_sign9 { get; set; }
        public string process_sign10 { get; set; }
        public string urgent_schedule_sign { get; set; }
        public string machine_set_up_sign { get; set; }
        public string final_sign { get; set; }
        public string jis_sign { get; set; }
        public string set_item_sign { get; set; }
        public string finished_goods_code { get; set; }
        public string customer_code { get; set; }
        public string limitation_item_sign { get; set; }
        public string mp_code { get; set; }
        public string enterprise_code { get; set; }
        public string line_group { get; set; }
        public string line_no { get; set; }
        public string press_no { get; set; }
        public string data_no { get; set; }
        public string mps_no { get; set; }
        public Nullable<double> co_qty { get; set; }
        public Nullable<int> co_due_date { get; set; }
        public string customer_order_no { get; set; }
        public string set_item_co_line_no { get; set; }
        public string round_unit { get; set; }
        public string packing_type { get; set; }
        public string packing_package_type { get; set; }
        public string packing_label_type { get; set; }
        public string packing_label_type_sign { get; set; }
        public Nullable<double> pack_qty { get; set; }
        public string box_label_type { get; set; }
        public string box_label_print_type { get; set; }
        public Nullable<double> box_qty { get; set; }
        public string vendor_code { get; set; }
        public string external_fabrication_po_no { get; set; }
        public string nickname_no { get; set; }
        public string material_mark1 { get; set; }
        public string compound_mark1 { get; set; }
        public string material_mark2 { get; set; }
        public string compound_mark2 { get; set; }
        public string metal_case_material_code { get; set; }
        public string spring_material_code { get; set; }
        public string other_material_type { get; set; }
        public string partial_shipment_sign { get; set; }
        public string delivery_type { get; set; }
        public string internal_order_from_plant_code { get; set; }
        public string cost_accounting_division { get; set; }
        public string internal_order_from_sector { get; set; }
        public string stock_item_sign { get; set; }
        public Nullable<int> cavity_qty { get; set; }
        public Nullable<int> mold_plate_qty { get; set; }
        public Nullable<int> rotation { get; set; }
        public Nullable<double> curing_qty { get; set; }
        public Nullable<double> good_item_qty { get; set; }
        public Nullable<double> carry_over_good_item_qty { get; set; }
        public string capability_sign { get; set; }
        public Nullable<int> curing_date { get; set; }
        public string order_type { get; set; }
        public Nullable<int> box_label_qty { get; set; }
        public Nullable<double> stock_in_order1 { get; set; }
        public Nullable<int> inspection_card_print_qty { get; set; }
        public string latest_label_sign { get; set; }
        public Nullable<double> latest_stock_in_order { get; set; }
        public string re_schedule_sign { get; set; }
        public string parts_purchase_order_sign { get; set; }
        public Nullable<int> planned_stock_in_date { get; set; }
        public Nullable<double> stock_in_order_qty { get; set; }
        public string special_specification_sign { get; set; }
        public string internal_important_sign1 { get; set; }
        public string first_mass_production_route { get; set; }
        public string coating_material_type { get; set; }
        public string mold { get; set; }
        public Nullable<double> pre_process_days { get; set; }
        public Nullable<double> post_process_day { get; set; }
        public string mold_divide_sign { get; set; }
        public string special_process_code { get; set; }
        public Nullable<int> job_tag_divide_qty { get; set; }
        public Nullable<int> extensive_job_scheduling_job_tag_qty { get; set; }
        public string good_item_control_sign { get; set; }
        public string press_no_2 { get; set; }
        public string press_no_3 { get; set; }
        public string press_no_4 { get; set; }
        public string press_no_5 { get; set; }
        public string press_no_6 { get; set; }
        public string press_no_7 { get; set; }
        public string press_no_8 { get; set; }
        public string lot_no { get; set; }
        public string paper_verification_mark { get; set; }
        public Nullable<int> paper_verification_no { get; set; }
        public string update_request_sign { get; set; }
        public string disposal_sign { get; set; }
        public string tnc_tag_no { get; set; }
        public string tnc_total_tag_no { get; set; }
        public string stock_data_type { get; set; }
        public string unit { get; set; }
        public string eng_code { get; set; }
    }
}
