//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_job_progress_nics
    {
        public string job_order_no { get; set; }
        public string parent_job_order_no { get; set; }
        public string finished_goods_code { get; set; }
        public string customer_code { get; set; }
        public Nullable<short> operation_sequence_00 { get; set; }
        public string line_group_00 { get; set; }
        public string line_no_00 { get; set; }
        public string operation_code_00 { get; set; }
        public string control_point_00 { get; set; }
        public Nullable<short> operation_sequence_01 { get; set; }
        public string line_group_01 { get; set; }
        public string line_no_01 { get; set; }
        public string operation_code_01 { get; set; }
        public string control_point_01 { get; set; }
        public Nullable<short> operation_sequence_02 { get; set; }
        public string line_group_02 { get; set; }
        public string line_no_02 { get; set; }
        public string operation_code_02 { get; set; }
        public string control_point_02 { get; set; }
        public Nullable<short> operation_sequence_03 { get; set; }
        public string line_group_03 { get; set; }
        public string line_no_03 { get; set; }
        public string operation_code_03 { get; set; }
        public string control_point_03 { get; set; }
        public Nullable<short> operation_sequence_04 { get; set; }
        public string line_group_04 { get; set; }
        public string line_no_04 { get; set; }
        public string operation_code_04 { get; set; }
        public string control_point_04 { get; set; }
        public Nullable<short> operation_sequence_05 { get; set; }
        public string line_group_05 { get; set; }
        public string line_no_05 { get; set; }
        public string operation_code_05 { get; set; }
        public string control_point_05 { get; set; }
        public Nullable<short> operation_sequence_06 { get; set; }
        public string line_group_06 { get; set; }
        public string line_no_06 { get; set; }
        public string operation_code_06 { get; set; }
        public string control_point_06 { get; set; }
        public Nullable<short> operation_sequence_07 { get; set; }
        public string line_group_07 { get; set; }
        public string line_no_07 { get; set; }
        public string operation_code_07 { get; set; }
        public string control_point_07 { get; set; }
        public Nullable<short> operation_sequence_08 { get; set; }
        public string line_group_08 { get; set; }
        public string line_no_08 { get; set; }
        public string operation_code_08 { get; set; }
        public string control_point_08 { get; set; }
        public Nullable<short> operation_sequence_09 { get; set; }
        public string line_group_09 { get; set; }
        public string line_no_09 { get; set; }
        public string operation_code_09 { get; set; }
        public string control_point_09 { get; set; }
        public Nullable<short> operation_sequence_10 { get; set; }
        public string line_group_10 { get; set; }
        public string line_no_10 { get; set; }
        public string operation_code_10 { get; set; }
        public string control_point_10 { get; set; }
        public Nullable<short> operation_sequence_11 { get; set; }
        public string line_group_11 { get; set; }
        public string line_no_11 { get; set; }
        public string operation_code_11 { get; set; }
        public string control_point_11 { get; set; }
        public Nullable<short> operation_sequence_12 { get; set; }
        public string line_group_12 { get; set; }
        public string line_no_12 { get; set; }
        public string operation_code_12 { get; set; }
        public string control_point_12 { get; set; }
        public Nullable<short> operation_sequence_13 { get; set; }
        public string line_group_13 { get; set; }
        public string line_no_13 { get; set; }
        public string operation_code_13 { get; set; }
        public string control_point_13 { get; set; }
        public Nullable<short> operation_sequence_14 { get; set; }
        public string line_group_14 { get; set; }
        public string line_no_14 { get; set; }
        public string operation_code_14 { get; set; }
        public string control_point_14 { get; set; }
        public Nullable<short> operation_sequence_15 { get; set; }
        public string line_group_15 { get; set; }
        public string line_no_15 { get; set; }
        public string operation_code_15 { get; set; }
        public string control_point_15 { get; set; }
        public Nullable<short> operation_sequence_16 { get; set; }
        public string line_group_16 { get; set; }
        public string line_no_16 { get; set; }
        public string operation_code_16 { get; set; }
        public string control_point_16 { get; set; }
        public Nullable<short> operation_sequence_17 { get; set; }
        public string line_group_17 { get; set; }
        public string line_no_17 { get; set; }
        public string operation_code_17 { get; set; }
        public string control_point_17 { get; set; }
        public Nullable<short> operation_sequence_18 { get; set; }
        public string line_group_18 { get; set; }
        public string line_no_18 { get; set; }
        public string operation_code_18 { get; set; }
        public string control_point_18 { get; set; }
        public Nullable<short> operation_sequence_19 { get; set; }
        public string line_group_19 { get; set; }
        public string line_no_19 { get; set; }
        public string operation_code_19 { get; set; }
        public string control_point_19 { get; set; }
        public Nullable<short> greasing_sign { get; set; }
        public string entry_day { get; set; }
        public string entry_time { get; set; }
        public string update_day { get; set; }
        public string update_time { get; set; }
        public string transaction_no { get; set; }
        public string disposal_sign { get; set; }
    }
}
