//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_metal_job_nics
    {
        public string record_status { get; set; }
        public Nullable<int> entry_date { get; set; }
        public Nullable<int> entry_time { get; set; }
        public Nullable<int> update_date { get; set; }
        public Nullable<int> update_time { get; set; }
        public string entry_terminal_id { get; set; }
        public string program_id { get; set; }
        public string update_user_code { get; set; }
        public string company_code { get; set; }
        public string plant_code { get; set; }
        public string parts_job_order_no { get; set; }
        public string data_transfer_complete_sign { get; set; }
        public string err_sign { get; set; }
        public string job_order_no { get; set; }
        public string divide_sign { get; set; }
        public string parts { get; set; }
        public string parts_specification_file_id { get; set; }
        public string finished_goods_code { get; set; }
        public string customer_code { get; set; }
        public string limitation_item_sign { get; set; }
        public string mps_no { get; set; }
        public string line_group { get; set; }
        public string line_no { get; set; }
        public string press_no { get; set; }
        public string vendor_code { get; set; }
        public string sector { get; set; }
        public string supply_type { get; set; }
        public string capability_sign { get; set; }
        public Nullable<int> curing_date { get; set; }
        public string order_type { get; set; }
        public Nullable<int> curing_qty { get; set; }
        public Nullable<int> good_item_qty { get; set; }
        public string final_sign { get; set; }
        public Nullable<int> planned_stockin_date { get; set; }
        public string parts_order_type { get; set; }
        public string parts_issue_type { get; set; }
        public string issue_place { get; set; }
        public Nullable<int> issue_order_date { get; set; }
        public Nullable<int> issue_qty { get; set; }
        public Nullable<int> issue_weight { get; set; }
        public string parts_line_group { get; set; }
        public Nullable<int> number_of_unit { get; set; }
        public Nullable<int> partsqty { get; set; }
        public Nullable<int> sub_job_tag_qty { get; set; }
        public Nullable<int> include_qty { get; set; }
        public string parts_material_code { get; set; }
        public string reschedule_sign { get; set; }
        public string parts_purchase_order_sign { get; set; }
        public Nullable<int> useful_limit { get; set; }
        public Nullable<int> remain_qty_before { get; set; }
        public Nullable<int> remain_qty_after { get; set; }
        public string purchase_order_type { get; set; }
        public string paper_type { get; set; }
        public string update_request_sign { get; set; }
        public string unit { get; set; }
        public string eng_code { get; set; }
    }
}
