//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_part_stat
    {
        public string wc { get; set; }
        public string item { get; set; }
        public Nullable<int> stat { get; set; }
        public string job_order_no { get; set; }
        public string insert_date { get; set; }
        public string update_date { get; set; }
        public string insert_time { get; set; }
        public string update_time { get; set; }
    }
}
